name: Deploy FlashMath to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          # Remove any leftover files from previous runs
          rm -rf $GITHUB_WORKSPACE/* || true
          rm -rf $GITHUB_WORKSPACE/.* || true

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: true

      - name: Prepare data directory
        run: |
          # Create persistent data directory on host for SQLite database
          sudo mkdir -p /opt/flashmath/data
          # Set ownership to nextjs user (UID 1001) used inside the container
          sudo chown -R 1001:1001 /opt/flashmath/data
          sudo chmod 755 /opt/flashmath/data

      - name: Build and Start Container
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        run: |
          # Stop and remove existing container
          docker compose down || true
          
          # Build fresh image with new code
          docker compose build --no-cache
          
          # Start container
          docker compose up -d
          
          # Cleanup old images
          docker image prune -f
