name: Deploy FlashMath to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          # Remove any leftover files from previous runs
          rm -rf $GITHUB_WORKSPACE/* || true
          rm -rf $GITHUB_WORKSPACE/.* || true

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: true

      - name: Ensure directories and SSL certificates
        run: |
          # Create data directory for SQLite bind mount
          mkdir -p ./data
          
          # Verify nginx config files exist (should be from checkout)
          if [ ! -f ./nginx/nginx.prod.conf ]; then
            echo "❌ ERROR: nginx/nginx.prod.conf not found after checkout!"
            ls -la ./nginx/
            exit 1
          fi
          
          # Create nginx subdirectories (NOT the config file!)
          mkdir -p ./nginx/ssl
          mkdir -p ./nginx/logs
          
          # Fix permissions for nextjs user (UID 1001)
          sudo chown -R 1001:1001 ./data 2>/dev/null || chown -R 1001:1001 ./data 2>/dev/null || true
          
          # Fix permissions for nginx logs (nginx user in container)
          chmod 755 ./nginx/logs
          
          # Generate self-signed SSL certificate if it doesn't exist
          if [ ! -f ./nginx/ssl/flashmath.crt ] || [ ! -f ./nginx/ssl/flashmath.key ]; then
            echo "🔐 Generating self-signed SSL certificate for flashmath.io..."
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
              -keyout ./nginx/ssl/flashmath.key \
              -out ./nginx/ssl/flashmath.crt \
              -subj "/C=US/ST=State/L=City/O=FlashMath/OU=Production/CN=flashmath.io" \
              -addext "subjectAltName=DNS:flashmath.io,DNS:www.flashmath.io,IP:127.0.0.1"
            echo "✅ SSL certificate generated"
          else
            echo "✅ SSL certificate already exists"
          fi
          
          # Create PostgreSQL and Redis volumes if they don't exist
          docker volume create flashmath_postgres_data 2>/dev/null || true
          docker volume create flashmath_redis_data 2>/dev/null || true

      - name: Build and Start Containers
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Stop existing containers gracefully
          docker compose down || true
          
          # Build fresh image with new code
          docker compose build --no-cache
          
          # Start all containers (flashmath, postgres, redis)
          docker compose up -d
          
          # Wait for services to be healthy
          echo "Waiting for services to start..."
          sleep 10
          
          # Check container status
          docker compose ps
          
          # Cleanup old images
          docker image prune -f

      - name: Verify deployment
        run: |
          # Wait for health check to pass using docker exec (not compose)
          echo "Verifying deployment..."
          for i in {1..30}; do
            # Use curl directly in container or check container health
            if docker exec flashmath node -e "require('http').get('http://127.0.0.1:3000/api/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); }).on('error', () => process.exit(1))" 2>/dev/null; then
              echo "✅ FlashMath is healthy!"
              exit 0
            fi
            echo "Waiting for FlashMath to be ready... ($i/30)"
            sleep 5
          done
          echo "❌ Health check failed after 150 seconds"
          docker logs flashmath --tail=50
          exit 1
