name: Deploy FlashMath to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          # Remove any leftover files from previous runs
          rm -rf $GITHUB_WORKSPACE/* || true
          rm -rf $GITHUB_WORKSPACE/.* || true

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: true

      - name: Ensure data directory has correct permissions
        run: |
          # Create data directory for SQLite bind mount
          mkdir -p ./data
          
          # Fix permissions for nextjs user (UID 1001)
          # Use sudo if available, otherwise try without
          sudo chown -R 1001:1001 ./data 2>/dev/null || chown -R 1001:1001 ./data 2>/dev/null || true
          
          # Create PostgreSQL and Redis volumes if they don't exist
          docker volume create flashmath_postgres_data 2>/dev/null || true
          docker volume create flashmath_redis_data 2>/dev/null || true

      - name: Build and Start Containers
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          # Stop existing containers gracefully
          docker compose down || true
          
          # Build fresh image with new code
          docker compose build --no-cache
          
          # Start all containers (flashmath, postgres, redis)
          docker compose up -d
          
          # Wait for services to be healthy
          echo "Waiting for services to start..."
          sleep 10
          
          # Check container status
          docker compose ps
          
          # Cleanup old images
          docker image prune -f

      - name: Verify deployment
        run: |
          # Wait for health check to pass
          echo "Verifying deployment..."
          for i in {1..30}; do
            if docker compose exec -T flashmath node -e "require('http').get('http://127.0.0.1:3000/api/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); }).on('error', () => process.exit(1))"; then
              echo "✅ FlashMath is healthy!"
              exit 0
            fi
            echo "Waiting for FlashMath to be ready... ($i/30)"
            sleep 5
          done
          echo "❌ Health check failed after 150 seconds"
          docker compose logs flashmath --tail=50
          exit 1
