name: Deploy FlashMath to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone (faster)

      - name: Ensure directories and SSL certificates
        run: |
          # Create data directory for SQLite bind mount
          mkdir -p ./data
          
          # Verify nginx config files exist (should be from checkout)
          if [ ! -f ./nginx/nginx.prod.conf ]; then
            echo "❌ ERROR: nginx/nginx.prod.conf not found after checkout!"
            ls -la ./nginx/
            exit 1
          fi
          
          # Create nginx subdirectories
          mkdir -p ./nginx/ssl
          mkdir -p ./nginx/logs
          
          # Fix permissions for nextjs user (UID 1001)
          sudo chown -R 1001:1001 ./data 2>/dev/null || chown -R 1001:1001 ./data 2>/dev/null || true
          chmod 755 ./nginx/logs
          
          # Generate self-signed SSL certificate if it doesn't exist
          if [ ! -f ./nginx/ssl/flashmath.crt ] || [ ! -f ./nginx/ssl/flashmath.key ]; then
            echo "🔐 Generating self-signed SSL certificate..."
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
              -keyout ./nginx/ssl/flashmath.key \
              -out ./nginx/ssl/flashmath.crt \
              -subj "/C=US/ST=State/L=City/O=FlashMath/OU=Production/CN=flashmath.io" \
              -addext "subjectAltName=DNS:flashmath.io,DNS:www.flashmath.io,IP:127.0.0.1"
          fi

      - name: Build and Start Containers
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          EMAIL_FROM: "FlashMath <auth-mailer@flashmath.io>"
          # Enable BuildKit for faster builds with better caching
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
          # Stop existing containers gracefully
          docker compose down || true
          
          # Build with cache (remove --no-cache for speed)
          # BuildKit will cache npm install layer if package.json unchanged
          docker compose build
          
          # Start all containers
          docker compose up -d
          
          # Wait for services to be healthy
          echo "Waiting for services to start..."
          sleep 10
          
          # Check container status
          docker compose ps
          
          # Cleanup old/dangling images (keep cache)
          docker image prune -f --filter "dangling=true"

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          for i in {1..30}; do
            if docker exec flashmath node -e "require('http').get('http://127.0.0.1:3000/api/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); }).on('error', () => process.exit(1))" 2>/dev/null; then
              echo "✅ FlashMath is healthy!"
              exit 0
            fi
            echo "Waiting for FlashMath to be ready... ($i/30)"
            sleep 5
          done
          echo "❌ Health check failed after 150 seconds"
          docker logs flashmath --tail=50
          exit 1
