name: Deploy FlashMath to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Reverting to the common default
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Start Container
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        run: |
          # Remove existing database to force fresh seed with admin account
          rm -f flashmath_db.json
          
          # Create empty database file for volume mount
          echo "{}" > flashmath_db.json
          
          # Build and start container
          docker compose build
          docker compose up -d
          
          # Cleanup old images
          docker image prune -f
