name: Deploy FlashMath to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare data directory
        run: |
          # Create data directory for SQLite database persistence
          mkdir -p data
          chmod 777 data

      - name: Build and Start Container
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        run: |
          # Build and start container
          docker compose build
          docker compose up -d
          
          # Cleanup old images
          docker image prune -f
